# Generated by Django 2.2.4 on 2019-08-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(choices=[('遅刻', 'DELAY'), ('休暇(午前)', 'MORNING_OFF'), ('休暇(午後)', 'NIGHT_OFF'), ('休暇', 'WHOLE_OFF'), ('その他', 'OTHER')], max_length=255)),
                ('date', models.DateTimeField(verbose_name='勤怠日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('送信先', 'TO'), ('個別送信先', 'CC'), ('リコンサイル用', 'BCC')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailNotify.Mail')),
            ],
        ),
        migrations.CreateModel(
            name='MailComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailNotify.Mail')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='address_to',
            field=models.ManyToManyField(to='mailNotify.MailAddress'),
        ),
    ]
